import type { Tool } from "@anthropic-ai/sdk/resources/messages";
import { z } from "zod";
import { lifeItemSchema } from "../../domain/life-items";
import { lifePatchSchema } from "../../domain/life-patch";

// Cosmetic names and new step identities are not required user choices.
// Keep the stored schema strict; the parser supplies these creation defaults.
const routineCreation = lifeItemSchema.options[1].extend({
  title: lifeItemSchema.options[1].shape.title.optional().describe("Optional name; defaults to Morning routine or Evening routine. Do not ask for a name."),
  steps: z.array(lifeItemSchema.options[1].shape.steps.element.omit({ id: true, completedOn: true })).max(30),
});
const lifeCreationSchema = z.union([routineCreation, ...lifeItemSchema.options.filter(schema => schema !== lifeItemSchema.options[1])]);

export const ASSISTANT_TOOLS: Tool[] = [
  { name: "grocery_add", description: "Add all explicitly requested grocery items in one atomic change, up to 20 items. Use for multi-item shopping lists instead of separate life_save calls. Each item must come from the current request or its directly referenced list; do not invent ingredients. Does not purchase anything or remove existing items.", input_schema: { type: "object", properties: { items: { type: "array", minItems: 1, maxItems: 20, items: { type: "string", minLength: 1, maxLength: 240 } } }, required: ["items"], additionalProperties: false } },
  { name: "get_rundown", description: "Read one combined daily or weekly rundown of the user's reminders, due tasks, active goals and live Google Calendar. Use for what is my day/week like, daily/weekly summaries, or combined lists. startDate is a YYYY-MM-DD date in the user's timezone; days is an integer from 1 through 7. Rest of this week ends on Sunday, never a rolling seven days; start today unless tomorrow is explicitly requested. On Sunday, tomorrow plus the rest of this week is ambiguous: ask which week. This week starts Monday, next week is the following Monday; a named week starts on its specified date. Ask if the date is ambiguous. Does not change anything or schedule recurring summaries. Preserve missing-data/truncation notices and distinguish undated tasks/goals from scheduled commitments. Calendar updates means the current agenda, not an event-change history.", input_schema: { type: "object", properties: { startDate: { type: "string", format: "date" }, days: { type: "integer", minimum: 1, maximum: 7 } }, required: ["startDate", "days"], additionalProperties: false } },
  { name: "food_search", description: "Search Open Food Facts packaged foods by term OR barcode. Returns nutrients per 100g or 100ml, sometimes unknown. Confirm the specific product, amount and units before logging. Never assume missing nutrients are zero. Scale each known nutrient by amount/100; preserve null values. Search does not log food.", input_schema: { type: "object", properties: { term: { type: "string" }, barcode: { type: "string" } }, additionalProperties: false } },
  { name: "life_list", description: "Read account-owned Tempo records before referring to or editing them. Supply kind and optionally exact id or 1–12 distinctive query words. Queries match all words across title/body/ingredients/instructions/date before limiting, for every kind. Returns {items,truncated,coverage,notice}, newest first, at most 20 records. Narrow the query if truncated; an empty topic result is not proof nothing was ever saved.", input_schema: { type: "object", properties: { kind: { type: "string", enum: ["routine", "food", "meal", "recipe", "workout", "note", "grocery"] }, id: { type: "string", format: "uuid" }, query: { type: "string", maxLength: 200 } }, required: ["kind"], additionalProperties: false } },
  { name: "life_save", description: "Create an explicitly requested Tempo routine, food log, dated meal plan, reusable recipe, workout, note or grocery. Creation only: existing items must use life_patch after life_list. Use recipe for save this meal for later; ask for missing ingredients or steps. When planning a saved recipe, read it first and pass sourceRecipeId so the server copies all ingredients without scaling. Save requested meal servings; omit if unknown. Do not confuse planned meals with eaten food. Never invent nutrients; save null unknown values when requested. New routine step IDs and completion state are server-owned. Dates use the account timezone. Do not store secrets or medical diagnoses.", input_schema: { type: "object", properties: { sourceRecipeId: { type: "string", format: "uuid", description: "Meal plans only: exact account-owned saved recipe ID whose full ingredients should be copied." }, data: z.toJSONSchema(lifeCreationSchema) }, required: ["data"], additionalProperties: false } },
  { name: "life_patch", description: "Edit one account-owned Tempo record after reading life_list in this turn. Pass its exact id/version and a patch containing kind plus ONLY fields the user requested to change; never resend unchanged fields. A serving-count change only sets servings, never ingredient amounts. The server preserves omitted fields. Routine stepChanges explicitly add/update/remove/reorder steps; additions receive server IDs, updates preserve IDs and completion dates. Never replace the steps array or write completedOn. A record's kind cannot change.", input_schema: { type: "object", properties: { id: { type: "string", format: "uuid" }, version: { type: "integer", minimum: 1 }, patch: z.toJSONSchema(lifePatchSchema) }, required: ["id", "version", "patch"], additionalProperties: false } },
  { name: "life_remove", description: "Remove a specific Tempo life item only when the user asks. Read life_list first for exact id and version.", input_schema: { type: "object", properties: { id: { type: "string", format: "uuid" }, version: { type: "integer", minimum: 1 } }, required: ["id", "version"], additionalProperties: false } },
  { name: "calendar_agenda", description: "Read events from the connected Google primary calendar within an explicit range of at most 31 days. Use before editing an event; use returned IDs only.", input_schema: {
    type: "object", properties: { start: { type: "string", format: "date-time" }, end: { type: "string", format: "date-time" } }, required: ["start", "end"], additionalProperties: false,
  } },
  { name: "calendar_change", description: "Propose a create, update, or delete of a personal calendar event. This requests confirmation; it does NOT apply the change yet. No invites, guests, or recurring-series edits. Use exact eventId from calendar_agenda for update/delete. Ask for missing date/time/duration.", input_schema: {
    type: "object", properties: { change: { type: "object", properties: {
      operation: { type: "string", enum: ["create", "update", "delete"] }, eventId: { type: "string" }, title: { type: "string" },
      start: { type: "string", format: "date-time" }, end: { type: "string", format: "date-time" },
    }, required: ["operation"], additionalProperties: false } }, required: ["change"], additionalProperties: false,
  } },
  { name: "connection_status", description: "Check which accounts and capabilities are actually connected. Never claim access to an app that is not connected.", input_schema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "recall_memories", description: "Read saved preferences, personal facts AND Thought inbox notes. For specific personal recall, supply query with 1–12 distinctive keywords, e.g. spare keys. All keywords match across note title/body; avoid full conversational sentences. Results are bounded: preserve incomplete-search notices, and never claim information was never saved just because no match returned.", input_schema: { type: "object", properties: { query: { type: "string", minLength: 1, maxLength: 200 } }, additionalProperties: false } },
  { name: "forget_memory", description: "Forget a saved fact when requested. Use recall_memories first, then its exact memoryId and expectedContent to remove that record. A query removes a specific matching topic (including one food from a preference list); never use a vague pronoun. Tasks, goals and notes have their own removal tools.", input_schema: { type: "object", properties: { query: { type: "string" }, memoryId: { type: "string", format: "uuid" }, expectedContent: { type: "string" } }, additionalProperties: false } },
  { name: "set_checkins", description: "Enable or disable optional proactive task coaching at the user's explicit request. This does not change their explicit reminders. Maximum 3 proactive messages per day with at least 2 hours between them; quiet hours and calendar availability still apply.", input_schema: {
    type: "object", properties: { enabled: { type: "boolean" }, dailyCap: { type: "integer", minimum: 1, maximum: 3 } }, required: ["enabled"], additionalProperties: false,
  } },
];

export { isReadOnlyAssistantCommand } from "../../domain/turn-write-policy";
