import type { Tool } from "@anthropic-ai/sdk/resources/messages";
import { z } from "zod";
import { lifeItemSchema } from "../../domain/life-items";

export const ASSISTANT_TOOLS: Tool[] = [
  { name: "get_rundown", description: "Read one combined daily or weekly rundown of the user's reminders, due tasks, active goals and live Google Calendar. Use for what is my day/week like, daily/weekly summaries, or combined lists. startDate is a YYYY-MM-DD date in the user's timezone; days is an integer from 1 through 7. Rest of this week ends on Sunday, never a rolling seven days; start today unless tomorrow is explicitly requested. On Sunday, tomorrow plus the rest of this week is ambiguous: ask which week. This week starts Monday, next week is the following Monday; a named week starts on its specified date. Ask if the date is ambiguous. Does not change anything or schedule recurring summaries. Preserve missing-data/truncation notices and distinguish undated tasks/goals from scheduled commitments. Calendar updates means the current agenda, not an event-change history.", input_schema: { type: "object", properties: { startDate: { type: "string", format: "date" }, days: { type: "integer", minimum: 1, maximum: 7 } }, required: ["startDate", "days"], additionalProperties: false } },
  { name: "food_search", description: "Search Open Food Facts packaged foods by term OR barcode. Returns nutrients per 100g or 100ml, sometimes unknown. Confirm the specific product, amount and units before logging. Never assume missing nutrients are zero. Scale each known nutrient by amount/100; preserve null values. Search does not log food.", input_schema: { type: "object", properties: { term: { type: "string" }, barcode: { type: "string" } }, additionalProperties: false } },
  { name: "life_list", description: "Read the user's Tempo routines, food logs, meal plans, workouts, notes or groceries. Read before edits; use returned IDs and versions. These are Tempo records, not third-party integrations.", input_schema: { type: "object", properties: { kind: { type: "string", enum: ["routine", "food", "meal", "recipe", "workout", "note", "grocery"] } }, required: ["kind"], additionalProperties: false } },
  { name: "life_save", description: "Save an explicitly requested Tempo routine, food log, meal plan, favorite recipe, workout, note or grocery. Use recipe for remember this meal, recipes I like, or save for later: it has no date; ask for ingredients or steps if missing. Use meal only for a dated plan. Never confuse planning a meal with logging food eaten. For edits read first and preserve fields not changed; pass exact id and version. Omit id/version for new items. Never invent nutrition numbers or log suggested food as eaten. Use null for unknown nutrition, especially when the user explicitly permits unknown values; do not ask them to repeat that choice. Routine steps need UUIDs and completedOn null until actually completed. Dates use the user's local date. Do not store medical diagnoses or secrets in notes.", input_schema: { type: "object", properties: { id: { type: "string", format: "uuid" }, version: { type: "integer", minimum: 1 }, data: z.toJSONSchema(lifeItemSchema) }, required: ["data"], additionalProperties: false } },
  { name: "life_remove", description: "Remove a specific Tempo life item only when the user asks. Read life_list first for exact id and version.", input_schema: { type: "object", properties: { id: { type: "string", format: "uuid" }, version: { type: "integer", minimum: 1 } }, required: ["id", "version"], additionalProperties: false } },
  { name: "calendar_agenda", description: "Read events from the connected Google primary calendar within an explicit range of at most 31 days. Use before editing an event; use returned IDs only.", input_schema: {
    type: "object", properties: { start: { type: "string", format: "date-time" }, end: { type: "string", format: "date-time" } }, required: ["start", "end"], additionalProperties: false,
  } },
  { name: "calendar_change", description: "Propose a create, update, or delete of a personal calendar event. This requests confirmation; it does NOT apply the change yet. No invites, guests, or recurring-series edits. Use exact eventId from calendar_agenda for update/delete. Ask for missing date/time/duration.", input_schema: {
    type: "object", properties: { change: { type: "object", properties: {
      operation: { type: "string", enum: ["create", "update", "delete"] }, eventId: { type: "string" }, title: { type: "string" },
      start: { type: "string", format: "date-time" }, end: { type: "string", format: "date-time" },
    }, required: ["operation"], additionalProperties: false } }, required: ["change"], additionalProperties: false,
  } },
  { name: "connection_status", description: "Check which accounts and capabilities are actually connected. Never claim access to an app that is not connected.", input_schema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "recall_memories", description: "Read saved preferences, foods, and personal facts. Use for questions about what you remember, food lists, and personalized planning.", input_schema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "forget_memory", description: "Remove saved memories matching the user's specific description, when explicitly requested.", input_schema: { type: "object", properties: { query: { type: "string" } }, required: ["query"], additionalProperties: false } },
  { name: "set_checkins", description: "Enable or disable optional proactive task coaching at the user's explicit request. This does not change their explicit reminders. Maximum 3 proactive messages per day with at least 2 hours between them; quiet hours and calendar availability still apply.", input_schema: {
    type: "object", properties: { enabled: { type: "boolean" }, dailyCap: { type: "integer", minimum: 1, maximum: 3 } }, required: ["enabled"], additionalProperties: false,
  } },
];

export function isReadOnlyAssistantCommand(type: string): boolean {
  return ["get_rundown", "food_search", "life_list", "list_tasks", "list_goals", "list_reminders", "recall_memories", "connection_status", "calendar_agenda"].includes(type);
}
